-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Waktu pembuatan: 20 Des 2023 pada 11.07
-- Versi server: 10.4.28-MariaDB
-- Versi PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dishcoverdb`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `Bahan`
--

CREATE TABLE `Bahan` (
  `id` varchar(191) NOT NULL,
  `nama` varchar(191) NOT NULL,
  `gambar` varchar(191) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data untuk tabel `Bahan`
--

INSERT INTO `Bahan` (`id`, `nama`, `gambar`) VALUES
('1', 'Kembang kol', 'https://storage.googleapis.com/bahan-icon-dishcover/kembangkol.png'),
('10', 'Terung', 'https://storage.googleapis.com/bahan-icon-dishcover/terung.png'),
('11', 'Timun', 'https://storage.googleapis.com/bahan-icon-dishcover/cucumber.png'),
('12', 'Tomato', 'https://storage.googleapis.com/bahan-icon-dishcover/tomato.png'),
('13', 'Wortel', 'https://storage.googleapis.com/bahan-icon-dishcover/wortel.png'),
('14', 'Ayam', 'https://storage.googleapis.com/bahan-icon-dishcover/ayam.png'),
('15', 'Sapi', 'https://storage.googleapis.com/bahan-icon-dishcover/sapi.png'),
('2', 'Broccoli', 'https://storage.googleapis.com/bahan-icon-dishcover/brokoli.png'),
('3', 'Kentang', 'https://storage.googleapis.com/bahan-icon-dishcover/kentang.png'),
('4', 'Kubis', 'https://storage.googleapis.com/bahan-icon-dishcover/Kubis.png'),
('5', 'Labu', 'https://storage.googleapis.com/bahan-icon-dishcover/pumpkin.png'),
('6', 'Lobak', 'https://storage.googleapis.com/bahan-icon-dishcover/lobak.png'),
('7', 'Paprika', 'https://storage.googleapis.com/bahan-icon-dishcover/paprika.png'),
('8', 'Pare', 'https://storage.googleapis.com/bahan-icon-dishcover/pare.png'),
('9', 'Telur', 'https://storage.googleapis.com/bahan-icon-dishcover/telur.png');

-- --------------------------------------------------------

--
-- Struktur dari tabel `Favourite`
--

CREATE TABLE `Favourite` (
  `id` varchar(191) NOT NULL,
  `user_id` varchar(191) NOT NULL,
  `recipe_id` varchar(191) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data untuk tabel `Favourite`
--

INSERT INTO `Favourite` (`id`, `user_id`, `recipe_id`) VALUES
('46ef4127-2e85-48ca-b64c-7876c9047462', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '11'),
('76d8cf5b-b405-406c-8725-33ba12574da5', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '10'),
('c6b1ed76-d1fd-4807-a540-0657e9943ea5', '112ba2ad-3066-4b6e-b2c2-fa9bab8bb720', '10'),
('d5242f22-0491-41af-a5ea-5d7876e5ad63', '112ba2ad-3066-4b6e-b2c2-fa9bab8bb720', '17');

-- --------------------------------------------------------

--
-- Struktur dari tabel `History`
--

CREATE TABLE `History` (
  `id` varchar(191) NOT NULL,
  `user_id` varchar(191) NOT NULL,
  `recipe_id` varchar(191) NOT NULL,
  `accessedAt` datetime(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data untuk tabel `History`
--

INSERT INTO `History` (`id`, `user_id`, `recipe_id`, `accessedAt`) VALUES
('3a64c907-826f-4080-8063-591ac97a42be', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '41', '2023-12-07 13:48:15.730'),
('53a30866-841c-4e92-8cbe-abae715c7ebc', '112ba2ad-3066-4b6e-b2c2-fa9bab8bb720', '22', '2023-12-10 04:35:59.518'),
('71f10453-70ba-40e0-95e3-83da6badad96', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '40', '2023-12-07 10:04:10.383'),
('9862807b-b9ec-400d-a2a5-92f151ac93c7', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '12', '2023-12-07 09:45:45.345'),
('a4fcab97-4d01-4eae-a934-2c9d6c221fb2', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '11', '2023-12-07 08:45:13.717'),
('bcaf1599-7f90-4f9b-af16-696d5fb103ad', 'fd3d56a0-3bea-40ff-9ce9-780046291d31', '33', '2023-12-07 13:53:44.973'),
('c53b1d7f-b989-4269-8e1e-c607c072a3d3', '112ba2ad-3066-4b6e-b2c2-fa9bab8bb720', '22', '2023-12-10 04:09:32.968');

-- --------------------------------------------------------

--
-- Struktur dari tabel `Pantry`
--

CREATE TABLE `Pantry` (
  `id` varchar(191) NOT NULL,
  `user_id` varchar(191) NOT NULL,
  `bahan_id` varchar(191) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Struktur dari tabel `Recipe`
--

CREATE TABLE `Recipe` (
  `id` varchar(191) NOT NULL,
  `name` varchar(191) NOT NULL,
  `description` text NOT NULL,
  `ingredients` text NOT NULL,
  `step` text NOT NULL,
  `urlimage` varchar(191) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data untuk tabel `Recipe`
--

INSERT INTO `Recipe` (`id`, `name`, `description`, `ingredients`, `step`, `urlimage`) VALUES
('﻿1', 'Ayam Woku Manado', 'Ayam Woku Manado adalah hidangan khas dari daerah Manado, Sulawesi Utara, Indonesia. Hidangan ini terkenal karena cita rasa yang khas dan bumbu yang melibatkan rempah-rempah yang kaya', '1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk Nipis--2 Sdm Garam--3 Ruas Kunyit--7 Bawang Merah--7 Bawang Putih--10 Cabe Merah--10 Cabe Rawit Merah (sesuai selera)--3 Butir Kemiri--2 Batang Sereh--2 Lembar Daun Salam--2 Ikat Daun Kemangi--Penyedap Rasa--1 1/2 Gelas Air--', 'Cuci bersih ayam dan tiriskan. Lalu peras jeruk nipis (kalo gak ada jeruk nipis bisa pake cuka) dan beri garam. Aduk hingga merata dan diamkan selama 5 menit, biar ayam gak bau amis.--Goreng ayam tersebut setengah matang, lalu tiriskan--Haluskan bumbu menggunakan blender. Bawang merah, bawang putih, cabe merah, cabe rawit, kemiri dan kunyit. Oh iya kasih minyak sedikit yaa biar bisa di blender. Untuk sereh nya di geprek aja terus di buat simpul.--Setelah bumbu di haluskan barulah di tumis. Jangan lupa sereh dan daun salamnya juga ikut di tumis. Di tumis sampai berubah warna ya 👌--Masukan ayam yang sudah di goreng setengah matang ke dalam bumbu yang sudah di tumis, dan diamkan 5 menit dulu. Biar bumbu meresap. Lalu tuangkan 1 1/2 Gelas air. Lalu tambahkan penyedap rasa (saya 3 Sdt, tapi sesuai selera ya) koreksi rasa dan Biar kan sampai mendidih--Setelah masakan mendidih, lalu masukan daun kemangi yang sudah di potong potong. Masak lagi sekitar 10 menit. And taraaaaaaaaaaaaaa..... jadi deh Ayam Woku Manadonya.--Oh iyaa kalo mau di tambahkan potongan tomat merah juga bisa ko. Sesuai selera aja yaa buibuuuu 👌👌👌--', 'https://img-global.cpcdn.com/recipes/4a0bb9e71ee86944/1360x964cq70/ayam-woku-manado-foto-resep-utama.webp'),
('10', 'Ikan Kembung Bakar Teflon', 'Ikan kembung bakar teflon adalah hidangan sederhana namun lezat yang dapat dengan mudah dibuat di rumah. Ikan kembung yang segar dilumuri dengan bumbu-bumbu yang kaya rasa, kemudian dipanggang dengan teflon hingga matang.', '1/2 kg ikan kembung sate, bersihkan--1 buah jeruk sate/jeruk kunci--1 sdm garam halus--2 sdt lada bubuk--1 sdm ketumbar bubuk--', 'Kucuri ikan dengan jeruk, diamkan 5 menit--Lumuri ikan dg garam, lada dan ketumbar bubuk, simpan d kulkas sekitar 30 menit--Bakar d atas teflon yg d olesi mentega/ butter tipis dengan api yg kecil--Balik untuk membakar kedua bagian ikan.--Sajikan dengan cocolan sambal kecap--', 'https://img-global.cpcdn.com/recipes/5cf72d705747b8ed/1360x964cq70/ikan-kembung-bakar-teflon-foto-resep-utama.webp'),
('11', 'Mujaer asam pedas manis', 'Mujair asam pedas manis adalah hidangan ikan yang populer di Indonesia. Hidangan ini terdiri dari ikan mujair yang digoreng, kemudian dimasak dengan saus asam, pedas, dan manis. Saus ini biasanya terbuat dari bawang merah, bawang putih, cabai merah, air asam jawa, gula merah, dan kecap manis. ', '1/2 kg ikan mujaer (stok gurame habis)--2 buah Wortel potong korek api--1 siung bawang bombai--7 siung bawang putih--13 cabai rawit--4 siung bawang merah--2 sendok makan Saos tomat--2 sendok makan Saos tiram--Garam--Merica--100 ml air matang--Jahe--Jeruk nipis--', 'Bersihkan ikan sampai benar-benar bersih. Kerat-kerat dagingnya. Beri garam, merica, potongan jahe perasan jeruk nipis, dan 2 siung bawang uleg. Diamkan 10 menit--Uleg 5 bawang putih yang tersisa. Potong bawang bombai dan dan bawang merah dan cabai rawit.--Goreng ikan mujaer hingga matang, lalu sisihkan.--Tumis bawang merah dan bawang bombai hingga wangi, masukkan bawang putih uleg. Tumis hingga wangi.--Masukkan wortel, tambahkan air. Aduk-aduk. Tunggu hingga wortel hampir matang.--Masukkan saos tomat dan saos tiram. Beri perasan jeruk nipis. Aduk-aduk Koreksi rasa. Jika sudah pas, masukkan ikan, aduk sebentar saja.--Siap disajikan.--', 'https://img-global.cpcdn.com/recipes/e6dd892ccd1ada2f/1360x964cq70/mujaer-asam-pedas-manis-foto-resep-utama.webp'),
('12', 'Gurame Asam manis', 'Gurame asam manis adalah salah satu hidangan khas Indonesia yang populer. Hidangan ini terdiri dari ikan gurame yang digoreng tepung, kemudian dimasak dengan saus asam manis yang terbuat dari tomat, nanas, cabai, dan bumbu-bumbu lainnya.', '1/2 kg ikan gurame--2 buah wortel (potong seperti batang korek api)--Bumbu--5 siung bawang merah--4 siung bawang purih--1 bh tomat--Cabe besar (selera brp j)--Cage kecil (selera brp j)--2 sacet Saos sambel--Saos tomat (q pakek Saos botolan)--Bahan tambahan--Tepung maezena--Kunir--Garam, gula, merica ladaku--', 'Uleg kunir sama garam kasih air lalu guraminya d rendam, diem in sekitar 10menitan lalu goreng gurame--Untuk Saos asam manis nya, gongso semua bumbu sampek harum, masukan wortel setelah itu kasih Saos Dan garam gula merica ladaku, rasain setelah pas rasanya baru masukan tepung meizena yg sudah d cairkan dengan air setelah mengental angkat--Tata gurame d atas piring siram saosnya Dan siap di santaaap...--', 'https://img-global.cpcdn.com/recipes/c44e9604c81ca033/1360x964cq70/gurame-asam-manis-foto-resep-utama.webp'),
('13', 'Asam padeh ikan tuna', 'Asam padeh ikan tuna adalah hidangan khas Sumatera Barat yang bercitarasa asam dan pedas. Hidangan ini terbuat dari ikan tuna yang dimasak dengan bumbu-bumbu khas Minang, seperti cabai merah, bawang merah, bawang putih, lengkuas, jahe, kunyit, dan asam kandis. Kuah asam padeh ikan tuna yang segar dan gurih berpadu dengan rasa pedas yang menggugah selera.', '1/2 kg ikan tuna--6 siung bawang merah--4 siung bawang putih--2 ruas kemiri--2 batang serai--2 ruas kunyit--2 ruas laos--4 lembar daun jeruk--1 lembar daun kunyit--2 buah asam Kandis--4 buah belimbing hulu--6 buah cabai merah (bisa disesuaikan)--10 buah cabai rawit (bisa disesuaikan)--3 gelas air--2 sendok garam--1/2 sendok gula--', 'Haluskan bumbu (cabai merah, kemiri, bawang, kunyit, Laos)--Tumis bumbu sampai berubah warna--Tambahkan air--Masukkan serai yg sudah di geprek, daun kunyit, daun jeruk, asam Kandis, belimbing hulu, dan cabai rawit utuh (tdk dihaluskan dan tdk dipotong)--Tunggu sampai mendidih--Setelah mendidih, masukkan ikan tuna (sudah dicuci bersih dan diberi air perasan jeruk)--Kemudian beri garam dan gula secukupnya--Tunggu sampai air sedikit berkurang dan mengental--Asam padeh ikan tuna siap disajikan--', 'https://img-global.cpcdn.com/recipes/bb1a457b2e4431fc/1360x964cq70/asam-padeh-ikan-tuna-foto-resep-utama.webp'),
('14', 'Avocado Tuna Salad', 'Salad tuna alpukat adalah hidangan salad yang lezat dan bergizi yang terbuat dari alpukat, tuna kaleng, dan sayuran segar. Alpukat memberikan rasa krim dan kaya, tuna memberikan protein, dan sayuran segar menambahkan tekstur dan rasa. Salad tuna alpukat dapat disajikan dengan dressing salad favorit Anda atau dimakan polos. ', '1 kaleng Tuna Chunks--2 butir telur rebus--3 buah kentang rebus--2 buah avocado--2 buah bawang merah--12 biji zaitun--1 buah timun--Sebongkol daun salada/lettuce--secukupnya Garam & merica--', 'Campur semuanya dalam baskom, kecuali biji zaitun, telur rebus. Lalu tambahkan garam & merica--Tuang dalam piring saji, atur irisan telur & biji zaitun. Siap disajikan.--', 'https://img-global.cpcdn.com/recipes/e445ec7ac91e4501/1360x964cq70/avocado-tuna-salad-foto-resep-utama.webp'),
('15', 'Lele Asam Manis', 'Lele asam manis adalah salah satu hidangan khas Indonesia yang populer. Hidangan ini terbuat dari ikan lele yang digoreng hingga garing, kemudian dimasak dengan saus asam manis yang terbuat dari bawang bombay, tomat, kecap manis, dan bumbu-bumbu lainnya. ', '1/2 kg Lele Segar--180 ml air--3 sdm kecap manis--1 sdm margarine/minyak--1/2 sdt saus tiram (optional)--Bumbu halus :--6 siung bawang merah--5 siung bawang putih--4 cabe merah (bisa lebih sesuai selera)--2 buah kemiri--1 sdt garam (sesuai selera)--1/2 sdt penyedap rasa (sesuai selera)--1/2 sdt gula pasir (sesuai selera)--', 'Cuci bersihbikan, lalu goreng ikan lele agak matang tapi jangan sampai renyah. Tiriskan--Sambil menunggu, haluskan semua bumbu di atas.--Panaskan wajan dengan margarin.--Masukkan bumbu halus ke dalam wajan sampai harum. Tambahkan kecap, saus tiram dan air--Setelah berbau harum, barulah ikan lele dimasukkan.--Tunggu sampai bumbu meresap serta tes rasa. Setelah air tnggal sedikit, angkat dan sajikan.. Semoga membantu..--', 'https://img-global.cpcdn.com/recipes/5977c8d0828a1070/1360x964cq70/lele-asam-manis-foto-resep-utama.webp'),
('16', 'Pempek kulit ikan tenggiri', 'Pempek kulit ikan tenggiri adalah salah satu varian pempek khas Palembang yang terbuat dari kulit ikan tenggiri giling. Pempek ini memiliki tekstur yang renyah di luar dan lembut di dalam. Rasanya gurih dan lezat, dan cocok disantap dengan cuko pempek yang asam, manis, dan pedas.', '500 gr kulit ikan tenggiri halu--200 cc air matang--1 sdt garam--1 sdt Penyedap/ kaldu jamur--1/2 sdt merica--1/2 sdt gula--60 ml santan kental--5 siung bawang putih--5 siung bawang merah--350 gr sagu tani--2 sdm terigu--100 gr sagu untuk balur--', 'Aduk ikan tambahkan air sedikit demi sedikit bersamaan dgn garam--Masukkan terigu bersama santan--Masukkan sagu--Balurin tangan dgn sagu bentuk adonan dgn sendok makan--Letakkan di piring yg ditabur sagu--Goreng minyak panas sampai mengembang--Dinginkan--Potong2 lalu goreng--Siap menggoyang lidah sajikan dgn cuko--', 'https://img-global.cpcdn.com/recipes/4bd6f18f1ae9bc1f/1360x964cq70/pempek-kulit-ikan-tenggiri-foto-resep-utama.webp'),
('17', 'Tumis Tongkol Petai', 'Tumis tongkol petai adalah salah satu hidangan khas Indonesia yang populer. Hidangan ini terbuat dari ikan tongkol, petai, dan bumbu-bumbu seperti bawang merah, bawang putih, cabai rawit, dan garam. Tumis tongkol petai memiliki cita rasa yang gurih dan pedas, dengan aroma khas petai yang menggugah selera.', '2 bungkus tongkol--2 cabe gendot--2 papan petai--2 cabe rawit--2 bh cabe merah--3 bh b. Merah--3 bh b. Putih--2 lembar daun salam--Secukupnya garam--Secukupnya gula putih--', 'Cuci bersih ikan tongkol, goreng sebentar--Iris b. Merah, b. Putih, cabe merah, cabe rawit, cabe gendot. Tumis--Masukan petai, tambahkan sedikit air. Masukan garam, gula pasir. Cek rasa. Sajikan--', 'https://img-global.cpcdn.com/recipes/1a8c23899aae072d/1360x964cq70/tumis-tongkol-petai-foto-resep-utama.webp'),
('18', 'Ikan Patin pedas manis', 'Ikan patin pedas manis adalah salah satu hidangan khas Indonesia yang sangat populer. Hidangan ini terbuat dari ikan patin yang dimasak dengan bumbu pedas manis. Ikan patin adalah ikan air tawar yang memiliki daging yang lembut dan gurih. Bumbu pedas manis yang digunakan dalam hidangan ini terdiri dari bawang merah, bawang putih, cabai, tomat, dan gula merah. ', '500 gr ikan patin--5 siung bawang merah iris tipis--4 siung bawang putih iris tipis--1/2 bawang bombay ukuran kecil iris tipis--Cabai merah keriting (sesuai selera) iris tipis--Cabai rawit setan (sesuai selera) biarkan utuh--1 ruas lengkuas digeprek--2 lembar daun jeruk--2 sendok makan kecap--3 batang bawang daun iris tipis--', 'Ikan patin yang sudah dicuci bersih, dilumuri garam kemudian digoreng setengah kering--Tumis irisan bawang merah, putih, bombay dan cabai sampai dengan harum--Masukkan ikan yang sudah digoreng sebelumnya, kemudian tambahkan sedikit air--Masukkan kecap, lengkuas, daun jeruk, garam dan gula. Koreksi rasa--Biarkan sampai dengan meresap ke dalam daging ikan, setelah benar2 meresap terakhir masukkan irisan bawang daun dan cabai rawit setan, kemudian angkat dan sajikan--', 'https://img-global.cpcdn.com/recipes/7e1b2fa2fc895690/1360x964cq70/ikan-patin-pedas-manis-foto-resep-utama.webp'),
('19', 'Gurame tahu tauco', 'Gurame tahu tauco adalah salah satu hidangan khas Indonesia yang sangat populer. Hidangan ini terdiri dari ikan gurame yang digoreng garing dan disajikan dengan saus tauco yang gurih dan pedas. Tahu goreng juga biasanya disajikan sebagai pelengkap. ', '1 ekor gurame--1 buah tahu kotak--1 buah jeruk nipis--1 buah bawang bombay--3 siung bawang putih--1 jari jahe--3 buah cabe hijau besar buang biji--2 buah cabe merah besar--5 sdm tauco--Kecap asin--Kecap manis--Saos tiram--Minyak wijen--1 sdt Angciu--', 'Balurin gurame dgn jeruk nipis goreng--Goreng tahu kotak 2--Tumis bawang 2 ngan masukkan tauco--Masukkan kecap dll--Tambahkan sedikit air--Siap disajikan test rasa kurang asin tambah garam ya kl tauconya asin gak usah pake garam lg--', 'https://img-global.cpcdn.com/recipes/3804a35fa9a2066b/1360x964cq70/gurame-tahu-tauco-foto-resep-utama.webp'),
('2', 'Ayam goreng tulang lunak', 'Ayam goreng tulang lunak adalah hidangan kuliner yang menggugah selera, terkenal dengan kelembutan dagingnya dan kelezatan kulit yang renyah. Potongan ayam dipersiapkan dengan sempurna, dicelup dalam campuran rempah-rempah khas, dan digoreng hingga keemasan. Proses penggorengan yang tepat menciptakan lapisan luar yang kriuk namun tidak terlalu berminyak, sementara bagian dalam daging tetap lembut dan juicy.', '1 kg ayam (dipotong sesuai selera jangan kecil2 ya)--2 batang serai (memarkan)--4 lembar daun jeruk--7 butir bawang putih (haluskan)--1 sdm ketumbar (haluskan)--3 ruas jari Laos (haluskan)--3 ruas jari kunyit (haluskan)--2 butir kemiri (haluskan)--secukupnya Garam--Secukupnya Air (tuk ukep ayam)--Secukupnya Minyak goreng--', 'Haluskan bumbu2nya (BaPut, ketumbar, kemiri, kunyit, Laos, garam) hingga halus, sisihkan--Campur kan bumbu halus tadi dengan ayam yg sudah dicuci bersih dan sudah dipotong didalam panci presto. Uleni sampai tercampur rata.--Tambahkan air hingga ayam tenggelam semua. Masukkan serai dan daun jeruk nya kedalam rendaman ayam. Tutup panci presto rebus/ ukep presto sampai kurleb 45 menit. Dengan api sedang.--Setelah proses ukep presto selesai, tunggu suhu dingin ruang. Lalu goreng ayam dengan minyak goreng api sedang sampai ayam berwarna kecoklatan.--Matang dan sajikan ayam selagi hangat bersama nasi putih, sambal dgn perasan jeruk nipis, lalapan.--', 'https://img-global.cpcdn.com/recipes/d820435f52622cdd/1360x964cq70/ayam-goreng-tulang-lunak-foto-resep-utama.webp'),
('20', 'Ikan Patin', 'Ikan patin adalah ikan air tawar yang berasal dari Asia Tenggara. Ikan ini memiliki tubuh yang panjang dan pipih, dengan kulit yang licin dan tidak bersisik. Ikan patin memiliki kepala yang kecil dengan mulut yang terletak di ujung kepala. Ikan ini memiliki empat pasang sungut yang berfungsi untuk mendeteksi mangsa. ', '5 potong Ikan patin--1 buah Jeruk nipis--1 buah Tomat uk. sedang--3 buah Cabai hijau keriting (boleh lebih)--2 buah Cabai rawit/ cengek (boleh lebih)--1 batang serai (geprek)--1/2 ruas Lengkuas (geprek)--Bumbu-bumbu dihaluskan--8 siung Bawang merah--2 siung Bawang putih--5 buah Kemiri--1 sdt Kunyit bubuk--1 buah Cabai merah besar--Nb: Jika hoby pedas, tambahkan cabai sesuai selera masing-masing 😊--', 'Cuci bersih dan lumuri ikan dengan garam, perasan jeruk nipis selama 15 menit.--Potong dan iris-iris tomat, cabai merah kecil, cabai rawit hijau dan lengkuas (geprek).--Haluskan bumbu - bumbu seperti bawang merah, bawang putih, kemiri, kunyit, cabai merah besar.--Tumis bumbu-bumbu halus serta cabai, serai, lengkuas dan tomat.--Kemudian masukkan ikan patin. Aduk-aduk rata dan masukkan air 250 ml. Aduk2 tercampur smw dan diamkan hingga air menyusut (bumbu-bumbu meresap). Masukkan garam, test rasa.--Angkat dan Sajikan...😄--', 'https://img-global.cpcdn.com/recipes/d921685d2e837a09/1360x964cq70/ikan-patin-foto-resep-utama.webp'),
('21', 'Gulai Ikan Kakap Merah khas Padang', 'Gulai Ikan Kakap Merah khas Padang adalah salah satu hidangan khas Padang yang kaya akan cita rasa. Gulai ini terbuat dari ikan kakap merah yang dimasak dengan bumbu rempah-rempah khas Padang, seperti cabai merah, kunyit, jahe, lengkuas, dan serai. Gulai ini memiliki cita rasa yang pedas, gurih, dan kaya rempah.', '2 ekor Ikan Kakap merah ukuran agak besar, potong 2--1/2 papan Tempe--Bumbu Halus :--10 siung Bawang merah--5 siung Bawang putih--4 cm Jahe--4 cm Kunyit--Bahan tambahan :--2 sdm Cabe giling halus--2 lbr Daun kunyit--8 lbr Daun jeruk--2 btg Sereh--4 lbr Daun salam--4 bh Asam kandis--Daun ruku ruku segenggam (bisa diganti daun kemangi)--15 butir Rawit merah--200 ml Santan kara--500 ml Air--', 'Tumis bumbu halus, cabe giling halus, daun kunyit, daun jeruk, daun salam, sereh dan asam kandis.--Masukkan santan cair (santan kara sebagian besar cairkan dengan air 500 ml sisanya di masukkan terakhir), daun ruku ruku dan cabe rawit.--Masukkan ikan, tempe, tunggu hingga mendidih kurang lebih 15 menit dengan api kecil.--Masukkan sisa santan kara yang masih kental, aduk2 sampai mendidih kembali.--Matikan api dan siap di sajikan.--', 'https://img-global.cpcdn.com/recipes/1ec9cec1874f16c5/1360x964cq70/2-gulai-ikan-kakap-merah-khas-padang-foto-resep-utama.webp'),
('22', 'Gurame crispy asam manis ala amih fatih', 'Gurame crispy asam manis ala amih fatih adalah sajian ikan yang lezat dan menggugah selera. Ikan gurame fillet dibalut tepung pedas dan digoreng hingga renyah, kemudian disiram dengan saus asam manis yang gurih dan manis. Tekstur ikan yang lembut dan renyah berpadu dengan rasa saus yang lezat, membuat sajian ini begitu nikmat. ', 'Bumbu ikan :--1 ekor ikan gurame fillet--1 buah jeruk nipis--1 sdt lada bubuk--1/2 sdt garam--1 siung bawang putih--1 pack tepung serbaguna pedas--1 buah telur kocok lepas--Saus :--1 buah bawang bombay iris--1 buah bawang putih iris--1 buah wortel potong sesuai selera--1 sdm saus tiram--5 sdm saus tomat--6 sdm saus sambal--secukupnya Gula--secukupnya Garam--secukupnya Lada--secukupnya Air--', 'Cuci bersih ikan gurame filletnya--Campurkan sampai merata ikan dengan perasan jeruk nipis, bawang putih, garam, lada--Diamkan 15-20 menit--Siapkan mangkok berisi telur yg sudah di kocok--Siapkan tepung serbaguna--Bila ikan sudah meresap, ambil ikan tersebut celupkan ke dalam telur lalu baluri dengan tepung serbaguna.--Panaskan minyak untuk menggoreng. Masukan ikan yg sudah dilumuri tepung, goreng dengan api sedang sampai warna berubah kecoklatan--Angkat dan sisihkan dulu--Selanjutnya panaskan minyak untuk menumis.--Masukkan bawang putih, bawang bombay. Masak hingga harum--Lalu masukkan saus tiram, saus tomat, saus sambal, air secukupnya. Aduk hingga rata--Masukkan gula, garam, lada, tes rasanya apakah sudah sesuai.--Masukkan wortel hingga matang.--Aduk terus supaya tidak gosong--Bila sudah matang angkat dan taruh di mangkok.--Sajikan ikan dengan dicocol saus asam manisnya atau disiram di atas ikannya--', 'https://img-global.cpcdn.com/recipes/d601c33b423708cd/1360x964cq70/gurame-crispy-asam-manis-ala-amih-fatih-foto-resep-utama.webp'),
('23', 'Balado Tongkol & Tahu', 'Balado tongkol dan tahu adalah salah satu hidangan khas Indonesia yang populer. Hidangan ini terbuat dari ikan tongkol yang digoreng setengah matang, kemudian dimasak dengan bumbu balado yang terbuat dari cabai merah keriting, bawang merah, bawang putih, dan rempah-rempah lainnya. Tahu yang ditambahkan ke dalam hidangan ini menambah tekstur dan rasa yang unik.', '1 buah ikan tongkol sedang (iris menjadi 10 Bagian)--5 buah tahu ukuran lecil--2 lembar daun jeruk--secukupnya Gula & garam--Bumbu halus :--5 buah bawang merah--2 buah bawang putih--10 Cabe Merah--5 cabe rawit--1 buah tomat--1 buah Gula merah ukuran sedang--', 'Bersihkan tongkol yang sudah di iris. Goreng sampai matang.--Potong dadu tahu (ukuran kecil), goreng hingga kering.--Tumis bumbu yang sudah dihaluskan hingga wangi, masukkan daun jeruk, gula dan garam. Masukan air secukupnya.--Masukkan tongkol & tahu yang sudah digoreng. diamkan hingga mendidih & bumbu meresap.--Sajikan dan siap dihidangkan. 😉--', 'https://img-global.cpcdn.com/recipes/33db4c3815aaeb02/1360x964cq70/balado-tongkol-tahu-foto-resep-utama.webp'),
('24', 'Sate Kambing', 'Sate kambing adalah salah satu makanan khas Indonesia yang paling populer. Makanan ini terbuat dari daging kambing yang dipotong-potong kecil, ditusuk dengan tusukan bambu, dan dibumbui dengan rempah-rempah. Setelah itu, sate kambing dibakar di atas bara api hingga matang.', 'Bahan-bahan :--500 gr Daging kambing--Daun pepaya--Bumbu yang dihaluskan :--4 siung bamer--4 siung baput--2 cm jahe--1 sdt ketumbar--1/2 sdt lada bubuk--1/2 sdt Garam--1 sdm air asam jawa--Bahan sambel kecap :--Kecap manis sesuai selera (aku pake bango)--Cabe rawit--Bamer--Tomat--Jeruk limau--', '1. Cuci bersih daging kambing, potong\" kotak, bungkus didalam lapisan daun pepaya (30menit)--2.setelah 30 menit, keluarkan daging dr daun pepaya, campurkan dengan bumbu yang sudah dihaluskan, diamkan 15 menit--3. Susun daging pada tusuk sate kurlen 4-5 potong per tusuk--4. Bakar (bisa pakai arang / teflon)--5. Bolak balik sate hingga benar\" matang--6. Sajikan dengan sambal kecap--', 'https://img-global.cpcdn.com/recipes/49ac24749ce7fee8/1360x964cq70/sate-kambing-foto-resep-utama.webp'),
('25', 'Rabeg Kambing', 'Rabeg kambing adalah hidangan khas Banten yang terbuat dari daging kambing yang direbus dengan bumbu-bumbu rempah yang kaya. Bumbu-bumbu yang digunakan antara lain bawang merah, bawang putih, cabai merah, jahe, kunyit, lengkuas, serai, dan berbagai rempah lainnya. Rabeg kambing memiliki cita rasa yang gurih, pedas, dan asam.', '1 kg daging kambing bagian paha beserta tulang--Bumbu halus--100 gr cabe--7 siung bawang putih--8 siung bawang mersh--7 butir kemiri--2 cm jahe--1 ruas kunyit--1/2 sdt klabet--1/2 sdt jinten--Bumbu lain--1 batang sereh--3 lembar daun salam--2 cm kayu manis--5 butir cengjeh--3 kapulaga hijau--5 sdm kecap manis--Garam--Gula--Pelengkap--Acar--Bawang goreng--', 'Tumis bumbu halus hingga harum. Masukan bumbu bumbu lain kecuali kecap.--Masukan daging kambing. Aduk sampai daging terbalut bumbu dan berubah warna--Pindahkan tumisan daging ke panci. Tambahkan air. Beri kecap gulz dan garam. Masak sampai daging empuk dan air tinggal sedikit--Sajikan dengan nasi dan pelebgkap--', 'https://img-global.cpcdn.com/recipes/a221d3fea2d62b9d/1360x964cq70/rabeg-kambing-foto-resep-utama.webp'),
('26', 'Gulai kambing', 'Gulai kambing adalah hidangan Indonesia tradisional yang terbuat dari daging kambing yang dimasak dengan bumbu gulai, yang terdiri dari rempah-rempah seperti kunyit, bawang merah, bawang putih, cabai, jahe, lengkuas, serai, dan ketumbar. Gulai kambing biasanya disajikan dengan nasi putih, lontong, atau ketupat.', '500 gram daging kambing--Bumbu :--sesuai selera Santan--2 btng serai,memarkan--5 lembar Daun Salam,jeruk--sesuai selera Cabe--2 btr Cengkeh--Bumbu halus:--5 siung bawng merah--4 siung bwng putih--5 butir kemiri--2 cm kunyit--2 cm jahe--2 cm lengkuas--1 sdt ketumbar--Mrica,pala,garam,gula seckpnya--', 'Rebus dgng kambing dgn jahe krng lbh 20 menit lalu buang airnya,cc bersih--Tumis bumbu yg sudah dihaluskn,,masukn semua bahan Dan bumbu--Rebus sampe empuk--Terakhir masukn santan,tes rasa,,,--Sajikan dimangkok,yumm ✌️--', 'https://img-global.cpcdn.com/recipes/f3be83b00dcad5a0/1360x964cq70/gulai-kambing-foto-resep-utama.webp'),
('27', 'Sayur tulang kambing', 'Sayur tulang kambing adalah hidangan berkuah yang terbuat dari tulang kambing, sayuran, dan bumbu-bumbu. Kuahnya yang gurih dan segar, serta daging kambing yang empuk, menjadikan sayur tulang kambing sebagai salah satu hidangan favorit masyarakat Indonesia. ', '1.5 kg tulang sumsum kambing(direbus dahulu)agar bau amis hilang--Kacang panjang--Pepaya muda--10 buah Cabe rawit--2 buah Cabe merah besar--2 buah Cabe hijau besar--5 bawang putih--5 bawang merah--2 miri--Garam--1 bungkus masako--1/2 sendok makan Gula putih--Minyak goreng--Irisan potongan bawang merah 5 siung--Irisan potongan bawang putih 5 siung--Santan kelapa--', 'Haluskan bawang merah 5 siung dan 5 bawang putih beserta cabe rawit dan miri.--Panaskan kompor ksh sedikit minyak goreng, masukkan irisan cabe besar merah, hijau serta bawang putih dan merah sampai setengah matang--Lalu masukkan cabe,miri,bawang merah dan bwang putih yg telah di haluskan,tumis sampai matang--Masukkan sedikit air pada tumisan tadi...lalu masukkan sayuran beserta tulang sumsum kambing yg sudah di rebus tadi--Terakhir masukkan santan, garam, 1bungkus masako, gula putih..tunggu sampai mendidih aduh terus agar santannya tidak pecah.--Matikan kompor...sayur tulang kambing siap di hidangkan--', 'https://img-global.cpcdn.com/recipes/f484a4b05bab5734/1360x964cq70/sayur-tulang-kambing-foto-resep-utama.webp'),
('28', 'Sate Kambing', 'Sate kambing adalah salah satu makanan Indonesia yang paling populer. Sate ini terbuat dari daging kambing yang dibumbui dengan rempah-rempah dan dibakar di atas bara api. Sate kambing biasanya disajikan dengan saus kacang atau kecap manis, serta lalapan seperti kubis, tomat, dan bawang merah. ', '300 garam daging kambing--1/2 buah jeruk nipis--secukupnya kecap manis--bumbu kacang:--100 gram kacang tanah goreng--3 siung bawang merah--2 siung bawang putih--1 buah cabe merah besar--5 buah cabe rawit merah (sesuai selera)--2 butir kemiri--4 lembar daun jeruk--200 ml air--2 sdm kecap manis--2 sdm gula merah iris--secukupnya garam--bahan tambahan :--acar wortel timun bawang cabe rawit--bawang goreng--', 'Potong daging kambing sesuai selera, beri perasan jeruk nipis, diamkan 10 menit, kemudian cuci bersih.. setelah itu tusukan daging pda tusuk sate--Buat bumbu kacang: 1. blender kacang tanah dengan air sampai halus. 2.haluskan bumbu (bawang cabe kemiri) tumis bumbu halus sampai harum. beri garam gula merah dan kecap.. aduk rata.. kemudian beri cairan kacang tanah.. aduk rata, koreksi rasa.. aduk terus agar tidak menggumpal... kekentalan saus kacang sesuai selera.. kemudian angkat.--Taruh dalam piring, saus kacang 3sdm dan kecap manis 3 sdm, aduk rata... baluri sate dengan bumbu ini sampai rata... kemudian bakar sampai matang...--Setelah matang sate disajikan demgan saus kacang, acar, bawang goreng, dan nasi/lontong.. nikmat satenya besar-besar.... 😁--', 'https://img-global.cpcdn.com/recipes/f01bb5615d3923af/1360x964cq70/sate-kambing-foto-resep-utama.webp'),
('29', 'Sop Kaki Kambing', 'Sop kaki kambing adalah hidangan berkuah yang terbuat dari kaki kambing yang direbus dengan berbagai bumbu rempah-rempah. Hidangan ini populer di Indonesia, terutama di daerah Jawa. Sop kaki kambing memiliki kuah yang gurih dan kaya rasa, dengan potongan kaki kambing yang empuk dan lembut. ', '4 kaki kambing--2-3 buah kentang, potpng dadu besar--3-4 batang daun bawang, iris 2 cm--2-3 L air panas--2-3 sdm minyak utk menumis--Bumbu halus:--4 buah bawang merah--8 buah bawang putih--1 sdm garam--1 sdt lada bubuk--1/2 sdt pala bubuk--Bumbu lainnya:--5 buah cengkeh--4 buah kapulaga india--1 batang kayu manis--2 buah star anise--4 lembar salam koja (bay leaves)--', 'Bakar kaki kambing utk menghilangkan bulu2 halus dan baunya. Kerok sesekali lalu celupkan ke air panas mendidih. Lakukan hingga kaki benar2 bersih. Lalu potong2 sesuai selera.--Panaskan minyak, tumis bumbu halus hingga harum. Masukan air panas dan bumbu lainnya. Masak hingga mendidih.--Masukan kentang dan kaki kambing. Masak hingga kentang matang dan kaki kambing empuk.--Masukan sisa bahan. Masak 3-4 menit lalu matikan api. Sajikan hangat.--', 'https://img-global.cpcdn.com/recipes/288ee0f94ce238f7/1360x964cq70/sop-kaki-kambing-foto-resep-utama.webp'),
('3', 'Ayam cabai kawin', 'Ayam cabai kawin merupakan varietas unik dari ayam yang dikenal karena warna bulunya yang mencolok dan paduan warna yang menyerupai cabai merah. Bulu-bulunya yang beragam menciptakan penampilan yang menarik dan menampilkan keindahan yang khas.', '1/4 kg ayam--3 buah cabai hijau besar--7 buah cabai merah rawit--3 siung bawang putih--2 siung bawang merah--secukupnya Gula--secukupnya Garam--1/4 buah tomat merah--secukupnya Air--secukupnya Minyak goreng--', 'Panaskan minyak di dalam wajan. Setelah minyak panas masukkan ayam yang sudah dipotong dadu. Goreng hingga matang. Lalu tiriskan.--Haluskan bawang putih, bawang merah, cabai hijau dan merah, tomat.--Panaskan minyak didalam wajan. Setelah minyak panas, masukkan bumbu yang sudah halus. Tunggu sampai wangi. Masukkan ayam yang sudah di goreng. Tambahkan air, gula dan garam. Tunggu sampai bumbu meresap di ayam. Sajikan.--', 'https://img-global.cpcdn.com/recipes/94c448501edbf8e4/1360x964cq70/ayam-cabai-kawin-foto-resep-utama.webp'),
('30', 'Kari kambing ala bundo', 'Kari kambing ala bundo adalah salah satu hidangan khas Indonesia yang sangat populer, terutama di Sumatra Barat. Hidangan ini terbuat dari daging kambing yang dimasak dengan bumbu kari yang kaya dan gurih. Bumbu kari yang digunakan biasanya terdiri dari kunyit, jahe, bawang merah, bawang putih, kemiri, ketumbar, jintan, dan merica. Selain itu, kari kambing ala bundo juga biasanya menggunakan santan untuk menambah kelembutan dan cita rasa. ', 'Daging kambing ½ kg, potong-potong, lumuri dengan sedikit bumbu halus dan biarkan 15 menit--10 siung bawang merah, iris halus--1 buah tomat, potong tipis--6 butir cengkeh--3 buah peka--5 buah kapulaga--9 siung bawang putih, iris halus--500 ml santan dari 1 butir kelapa (1,5 bungkus segitiga santan kemasan)--150 ml susu cair--500 ml air--3 ruas jari kayu manis--2 lembar daun jeruk purut buang tulangnya--10 lembar daun kari--1 sdt  Garam dan gula sedikit hanya untuk menambah rasa--secukupnya Minyak goreng--Bumbu halus:--1/2 sendok teh jinten, sangrai--1 sendok teh adas, sangrai--10 siung bawang merah--15 buah cabai merah--10 buah cabai rawit merah--6 siung bawang putih--1 sendok makan ketumbar, sangrai--2,5 cm/ 1 ruas jari  jahe--5 cm/ 2 ruas jari  kunyit (diameter kecil)--2,5 cm/ 1 ruas jari  lengkuas--', 'Tumis hingga harum bawang merah iris, bawang putih, kayu manis, cengkeh, peka, kapulaga kemudian masukkan bumbu halus, masukkan daun jeruk dan daun kari,--Masukkan daging kambing dan buah tomat, masak hingga daging kambing berubah warna dan keluar airnya--Tambahkan air, masak hingga setengah matang--Masukkan santan dan susu cair, masak hingga matang atau empuk.--Daging kari kambing siap dihidangkan bersama acar, roti pratha dan es thai tea.--', 'https://img-global.cpcdn.com/recipes/f916dcc03a9e8822/1360x964cq70/kari-kambing-ala-bundo-foto-resep-utama.webp'),
('31', 'Tongseng kambing presto', 'Tongseng kambing presto adalah hidangan khas Indonesia yang berasal dari Jawa Tengah. Hidangan ini terdiri dari daging kambing yang dimasak dengan kuah santan, cabai, bawang merah, bawang putih, dan rempah-rempah lainnya. Tongseng kambing presto biasanya disajikan dengan nasi putih, kerupuk, dan taburan bawang goreng. ', '250 gram iga kambing / daging kambing--200 gram kol--bumbu halus :--4 siung bawang merah--4 siung bawang putih--1 ruas kunyit bakar--3 buah kemiri sangrai--1 sdt ketumbar sangrai--1/2 sdt jinten--2 buah cabe merah besar--1 ruas jahe--bumbu tambahan:--4 lembar daun jeruk--2 batang sereh--1 ruas lengkuas--2 batang daun bawang--2 buah tomat--5 buah cabe rawit merah--2 sdm santan kara--secukupnya gula garam--', 'Potong daging kambing sesuai selera, cuci bersih kemudian masukan ke panci presto.--Masukan bumbu halus yg sudah ditumis, tambahkan air, sampai daging kambing terendam semua... tambahkan daun jeruk, sereh, lengkuas, masak sesuai petunjuk panci presto.. (me: 20 menit dari keluar uap pertama)--Sambil menunggu, rajang halus daun bawang, belah 4 tomat, potong kasar kol, cairkan santan dengan 300ml air.--Setelah 20 menit, matikan kompor, tunggu sampai uap habis.--Buka tutup panci, beri santan, kol, daun bawang, dan tomat, cabe rawit sesuai selera, aduk rata.. beri gula garam.. koreksi rasa.. masak sampai mendidih.. angkat dan sajikan..--Beri taburan bawang goreng.. makan dengan nasi hangat... 😋😋--', 'https://img-global.cpcdn.com/recipes/4267e0078750b3c4/1360x964cq70/tongseng-kambing-presto-foto-resep-utama.webp'),
('32', 'Telor dadar otak kambing', 'Telur dadar otak kambing adalah hidangan khas Indonesia yang terbuat dari telur ayam yang dicampur dengan otak kambing yang telah direbus dan dipotong-potong. Hidangan ini memiliki cita rasa yang gurih dan lezat, dengan tekstur otak kambing yang lembut dan creamy. Telur dadar otak kambing biasanya disajikan sebagai lauk pauk atau camilan.', 'Otak kambing--2 butir telor ayam--Penyedap masako--3 siung Bawang merah--1 siung Bawang putih--Daun bawang secukupnnya--Cabe rawit 3 biji adanya--Garam--1 lembar Daun salam--Jahe kunyit seujung jari kelingking dikit aja--Minyak untuk numis--', 'Cuci otak. Kambing smpe bersih cuci semua bumbu--Geprek jahe kunyit dan campurkan ke otak kambing jgn lupa daun salam lalu kukus sekitar 15 menit kurg lbh--Bawang merah putih cabe daun bawang di iris ya ke mangkok lain campur semua bahan kecuali salam buang aja krna itu bekas kukusan aduk bersama telor otak kambing--Lalu goreng smpe. Kekuningan ya--Angkat tiriskan siap di santap pake nasi anget sedapp selamat mencoba--', 'https://img-global.cpcdn.com/recipes/6296c6755d789af6/1360x964cq70/telor-dadar-otak-kambing-foto-resep-utama.webp\r'),
('33', 'Martabak tahu pedas kulit lumpia', 'Martabak tahu pedas kulit lumpia adalah camilan khas Indonesia yang terbuat dari tahu putih, kulit lumpia, dan bumbu-bumbu pedas. Martabak ini memiliki tekstur yang renyah di luar dan lembut di dalam. Rasanya gurih, pedas, dan menggugah selera. ', '12 lembar kulit lumpia--4 buah tahu putih--2 batang daun bawang (iris halus)--1 batang daun seledri (iris halus)--3 btr telur (sy pakai 2 aja krn agak besar)--1 sdm terigu + 2 sdm air (sbgai lem kulit lumpia)--Sckpnya minyak utk menggoreng--Bumbu halus :--3 siung bawang putih--1/2 bks lada/merica bubuk--Sckpnya garam gula dan kaldu bubuk--3-4 cabe merah kriting iris serong--2 buah wortel agak kecil parut kasar--', 'Haluskan tahu putih campur semua bahan kecuali kulit lumpia (icip rasa)--Ambil 1 lbr kulit lumpia beri 1 sdm adonan tahu ditengahnya lalu lipat (seperti amplop) dgn rapi, lalu beri lem disetiap sisisnya spy tdk terbuka pd saat digoreng, lakukan hingga habis--Panaskan minyak diatas wajan dgn api sedang cenderung kecil, goreng martabak sampai kecoklatan angkat dan tiriskan (abaikan wajannya yg sdh mulai jelek ya 😁)--Martabak tahu pedas kulit lumpia siap dihidangkan--Selamat mencoba... 😘😘--', 'https://img-global.cpcdn.com/recipes/936660f7ef7182e0/1360x964cq70/martabak-tahu-pedas-kulit-lumpia-foto-resep-utama.webp\r'),
('34', 'Batagor (Bakso Tahu Goreng) ala rumahan anti gagal', 'Batagor atau bakso tahu goreng adalah salah satu jajanan khas Bandung yang sangat populer. Makanan ini terbuat dari adonan tahu yang dicampur dengan bumbu-bumbu, kemudian dibentuk dan digoreng. Batagor memiliki tekstur yang renyah di luar dan lembut di dalam. Rasanya gurih dan lezat, cocok dinikmati dengan saus kacang atau sambal.', 'Bahan batagor--3 kotak ukuran kecil tahu kuning--5 sdm tepung terigu--1/2 sdm mentega (supaya kriuk2)--2 buah bawang putih--Garam (secukupnya)--Merica (secukupnya)--Air putih matang (secukupnya)--Bahan saus--2 sdm saus cabe (saya pake indofo**)--1/2 siung bawang putih--2 cabe rawit (sesuai selera ya karna suami saya gak suka pedas)--Kecap (secukupnya)--Air matang (secukupnya)--', 'Haluskan tahu kuning, bawang putih, garam merica (hingga lumat)--Tambahkan mentega, tepung terigu kedalam adonan tahu dan beri air hingga lembek tapi jangan sampai encer ya. Koreksi rasa--Siapkan wajan dengan minyak, goreng adonan yang telah dibuat. (Saya pake 2 sendok buat bikin kecil2). Angkat dan tata di mangkuk.--Haluskan bawang putih, cabai rawit--Tumis bawang putih dan cabai yang sudah di haluskan hingga harus.--Masukkan saus, kecap, garam. Koreksi rasa--Batagor dan sausnya siap untuk dinikmati 🤤--', 'https://img-global.cpcdn.com/recipes/050d52c923af4136/1360x964cq70/batagor-bakso-tahu-goreng-ala-rumahan-anti-gagal-foto-resep-utama.webp\r'),
('35', 'Sayur Sutace (sop tahu ceker)', 'Sayur Sutace (sop tahu ceker) adalah salah satu hidangan sup tradisional Indonesia yang terbuat dari tahu, ceker ayam, dan berbagai macam sayuran. Sup ini memiliki cita rasa yang gurih dan segar, dengan tekstur yang lembut dan empuk. Sayur Sutace biasanya disajikan dengan nasi hangat atau lontong.', '1/2 kg ceker ayam--4 buah wortel ukuran sedang--6 buah wortel--sesuai selera Kol--sesuai selera Daun bawang--sesuai selera Seledri--4 buah tahu kuning--Garam--Gula putih--Penyedap rasa (ma**ko)--Lada bubuk--Jeruk nipis--2 siung Bawang Putih--2 siung Bawang merah--', 'Bersihkan ceker, lau rebut selama 3-4 menit pakai jeruk nipis biar gk terlalu bau--Tiriskan ceker--Potong2 tahu, lalu goreng set mateng, tiriskan--Potong2 sayurr, cuci hingga bersihh.--Haluskan bawang merah dan bawang putih.--Panaskan sedikit minyak masukan bawang yg sudah di haluskan, oseng2 hingga tercium wangi--Masukan sayurr, tampahkan air, garam, gula putih dan penyedap rasa secukupnya.--Tunggu hingga sayur hampir matang, masukan ceker, dan tahu.--Tutup wajan hingga kaldu meresap kedalam ceker dan tahu.--Setelah matang, tuang ke mangkok, siap di santappp 😊😊--', 'https://img-global.cpcdn.com/recipes/243902d56587e631/1360x964cq70/sayur-sutace-sop-tahu-ceker-foto-resep-utama.webp\r'),
('36', 'Sapo Tahu Ayam ala Mey👌', 'Sapo Tahu Ayam ala Mey adalah salah satu hidangan Chinese food yang populer di Indonesia. Hidangan ini terbuat dari tahu yang digoreng, ayam, dan berbagai macam sayuran, seperti sawi hijau, wortel, dan jamur. Semua bahan ini dimasak dalam kuah kaldu ayam yang gurih dan lezat. ', '1 bks Tofu--5-10 bh filet ayam--1 bh wortel, iris tipis menyerong--5 bh jagung muda, iris tipis menyerong--1/2 kuntum bunga kol, pisahkan jd kuntum2 kecil--5 lbr pakcoy, iris 4-5 bag/lbr--2 lbr daun kol, iris2--2 sdm saos tiram--3 sdm kecap asin--1-2 sdm Royco ayam--1,5 gls air--Pengental : 1/2 gls air + 1 sdm sagu--Bumbu halus :--7 bh bamer--4 bh baput--1 sdt lada halus--Minyak utk menumis--', 'Iris tofu, jgn terlalu tipis, nanti hancur, goreng..,sisihkan--Siapkan sayur2annya, cuci, iris2, sisihkan (ups: pakcoynya hampir kelupaan)--Tumis bumbu halus, dgn api kecil, hingga matang, masukkan filet ayam, aduk2 beri air, masak sampai mendidih--Masukkan irisan wortel, jagung & brokoli, aduk tutup, biarkan sayur2an lunak & matang--Beri saos tiram, kecap asin & Royco, aduk2--Masukkan pakcoy & kol, aduk2, terakhir masukkan pengental, aduk rata, koreksi rasa--Sayuran pindahkan kepiring/mangkok, tata tofu goreng diatasnya, siram dgn saosnya--Sajikan--Ini foto sapo tahu yg pertama sekali buat pagi tadi #dibuangsayang--', 'https://img-global.cpcdn.com/recipes/7fd5af09edb43f4e/1360x964cq70/sapo-tahu-ayam-ala-mey-foto-resep-utama.webp\r'),
('37', 'TTKK (tahu telur timun tauge kuah kacang)', 'TTKK (tahu telur timun tauge kuah kacang) adalah sajian kuliner khas Indonesia yang sederhana namun lezat. Hidangan ini terdiri dari tahu goreng, telur rebus, tauge, timun, dan kuah kacang yang gurih dan nikmat. ', '1 butir telur--1 tahu--secukupnya Timun--secukupnya Tauge--Kuah kacang :--Kacang tanah disangrai--Bawang merah--Bawang putih--Cabe kering--Cabe rawit--Gula merah--', 'Goreng tahu dan telur, rebus tauge.--Potong2 timun sesuai selera--Tata telur pada piring, potong tahu taruh diatas telur tadi lalu tauge dan timun lalu airam kuah kacang--TTKK siap disantap--', 'https://img-global.cpcdn.com/recipes/394ff3287cc91456/1360x964cq70/ttkk-tahu-telur-timun-tauge-kuah-kacang-foto-resep-utama.webp\r'),
('38', 'Perkedel Tahu Wortel Sederhana', 'Perkedel tahu wortel adalah salah satu camilan atau lauk pauk yang populer di Indonesia. Makanan ini terbuat dari tahu dan wortel yang dihaluskan kemudian dicampur dengan tepung dan bumbu-bumbu. Perkedel tahu wortel memiliki tekstur yang renyah di luar dan lembut di dalam. Rasanya gurih dan lezat, cocok dinikmati dengan nasi hangat atau sambal. ', '1 bks tahu putih--1 batang wortel (potong kecil-kecil)--1/2 bks Masako ayam--secukupnya Lada bubuk--1 btr telur ayam (kocok)--2 sdm terigu--Minyak untuk menggoreng--', 'Hancurkan tahu dalam baskom--Campurkan wortel yang telah di potong-potong, lada bubuk, masako, telur dan terigu--Uleni hingga semua tercampur--Ambil menggunakan sendok makan, masukkan ke dalam minyak panas, goreng hingga berwarna kecoklatan.--', 'https://img-global.cpcdn.com/recipes/9d6f0edbbc15ff9a/1360x964cq70/perkedel-tahu-wortel-sederhana-foto-resep-utama.webp\r'),
('39', 'Kari tahu telur kentang', 'Kari tahu telur kentang adalah salah satu hidangan kari yang populer di Indonesia. Hidangan ini terbuat dari tahu, telur, dan kentang yang dimasak dengan kuah kari yang gurih dan kaya rempah. Kari tahu telur kentang biasanya disajikan dengan nasi hangat.', '4 butir telur rebus--4 buah tahu, potong 8 bagian lalu goreng berkulit--2 buah kentang, potong 4 bagian--1 bks santan kara ukuran kecil--1000 ml air / kaldu--5 buah cengek utuh (tambahan dari saya)--Haluskan :--1 buah cabe merah buang biji--5 siung bawang merah--2 siung bawang putih--1 sdm bumbu kari instant--2 butir kemiri--1/4 sdt ketumbar--1/2 sdt merica bubuk--1/8 sdt pala bubuk--2 ruas jari kunyit--Rempah cemplung--1 batang sereh, geprek--2 cm lengkuas--1 cm jahe--2 lembar daun jeruk--1 lembar daun salam--Secukupnya asam jawa--Garam / kaldu bubuk--Gula pasir--', 'Tumis bumbu halus dan rempah cemplung hingga harum dan matang--Masukan kentang. Aduk rata--Beri air. Setelah agak mendidih masukan telur, tahu dan rawit utuh--Bumbui garam dan gula pasir--Setelah didih, masukan santan, aduk sesekali--Angkat, sajikan dengan pelengkap--', 'https://img-global.cpcdn.com/recipes/cbe23554ba169378/1360x964cq70/kari-ayam-dan-tahu-foto-resep-utama.webp\r'),
('4', 'Ayam Geprek', 'Ayam Geprek adalah hidangan kuliner Indonesia yang telah menjadi favorit di kalangan pecinta makanan pedas. Hidangan ini terdiri dari potongan ayam goreng yang digeprek atau dihancurkan, kemudian disajikan dengan sambal pedas yang khas. Ayam Geprek memiliki cita rasa yang unik, kombinasi antara kelezatan daging ayam yang renyah dengan sensasi pedas yang menggigit.', '250 gr daging ayam (saya pakai fillet)--Secukupnya gula dan garam--50-100 gr tepung ayam serbaguna--Secukupnya lalapan (kemangi,kol,timun)--Secukupnya minyak panas--❤sambal korek--Secukupnya cabe rawit merah dan bwg putih--', 'Goreng ayam seperti ayam krispi--Ulek semua bahan sambal kemudian campur dengan minyak panas bekas goreng ayam--Geprek ayam kemudian campur dengan sambal,sajikan dengan lalapan ❤--', 'https://img-global.cpcdn.com/recipes/be1dca0c334edb6e/1360x964cq70/ayam-geprek-foto-resep-utama.webp\r'),
('40', 'Sundubu Jjigae (sup tahu pedas ala2 korea)', 'Sundubu Jjigae adalah sup tahu pedas ala Korea yang terbuat dari tahu sutera, gochujang (pasta cabai Korea), kecap asin, dan berbagai bahan pelengkap lainnya seperti daging, seafood, atau sayuran. Sup ini memiliki tekstur yang lembut dan gurih, dengan rasa pedas yang menggugah selera. ', '1 bungkus tahu putih, potong2 besar--1/2 ons toge--1/2 ons kol--1-2 ons sawi putih--1 tangkai daun bawang, iris serong agak tebal--1/2 bulat bawang bombay, iris memanjang--2-3 botol air--2-3 sdm perasan jeruk nipis/limau/lemon--1 telur, kocok lepas--Bumbu halus :--3 cabe merah besar--3 cengek merah (ini pedesnya sedang)--3 bawang merah--1 bawang putih--1 tomat sedang--', 'Haluskan bumbu (blender).--Tumis bawang bombay sampai harum, lalu masukkan bumbu halus, beri air, tumis sampai bumbu matang--Baru masukkan sayuran dan tahu, perasan jeruk, gula, kaldu ayam, garam, tes rasa.--Kalo udah dirasa pas dan matang baru masukkan kocokan telur, aduk2 sampai telur matang, lalu matikan api. Langsung beri daun bawang atasnya. Selesai.--', 'https://img-global.cpcdn.com/recipes/18c25a163cccc5b7/1360x964cq70/sundubu-jjigae-sup-tahu-pedas-ala2-korea-foto-resep-utama.webp\r'),
('41', 'Nugget Tahu Ekonomis Anti Gagal', 'Nugget tahu ekonomis anti gagal adalah camilan yang lezat dan bergizi. Terbuat dari tahu yang dihaluskan dan dicampur dengan berbagai bumbu, nugget tahu ini memiliki rasa yang gurih dan renyah. Proses pembuatannya pun mudah dan tidak memerlukan banyak bahan.', '5 buah tahu(1kg an) sy: sekitar 700g--1 butir telur--4 siung bawang putih, haluskan--1/2 bks ladaku--Secukupnya garam(sy: garam di skip)--2 bks royco sapi(sy: 1 bks)--2 buah wortel,kupas kulitnya, lalu parut--1 btg daun bawang, iris halus--Bahan pelapis:--Secukupnya telur, kocok lepas--Secukupnya tepung roti/panir/bread crumb--', 'Cuci tahu dan tiriskan. Agar saat digoreng tidak rapuh atau nyemek.--Haluskan tahu, lalu beri semua bumbu kecuali bahan pelapis. Aduk rata.(bisa koreksi rasa ketika telur belum ditambahkan, garam bisa disesuaikan karna setiap tahu ada yg asin dan tawar)--Oles cetakan dengan minyak sayur. Masukkan adonan tahu lalu kukus selama 35 menit atau sampai matang. Tutup kukusan dilapisi serbet agar air tidak menetes.--Setelah matang tunggu hingga dingin.--Setelah dingin potong2. Siapkan bahan pelapis. Celupkan ke telur lalu ke tepung roti lakukan sampai habis. Nugget bisa langsung digoreng atau disimpan di frezzer. Sebaiknya menyimpan nugget tidak ditumpuk apabila ditumpuk alasi dengan kertas minyak/kertas roti agar tidak lengket.--Goreng di api sedang. Lakukan satu balikan bila satu sisi sudah kering. Agar tidak menyerap banyak minyak.--Sajikan hangat dengan saus sambal😄. Lebih enak lagi bila ditambah keju dan kornet😍. Next time dicoba pakai keduanya😊.--', 'https://img-global.cpcdn.com/recipes/4c67c5bb47d53b6d/1360x964cq70/nugget-tahu-ekonomis-anti-gagal-foto-resep-utama.webp\r'),
('42', 'Tahu Petis musim ujan', 'Tahu petis adalah salah satu kuliner khas Indonesia yang populer di berbagai daerah, salah satunya di Jawa Tengah. Kuliner ini terbuat dari tahu goreng yang disajikan dengan siraman petis, bawang goreng, dan cabai rawit. Tahu petis biasanya disantap saat musim hujan karena rasanya yang hangat dan lezat.', '1 sdm petis--2 bh cabe rawit,rajang--2 bwg pth,rajang halus--4 bwg mrh,rajang halus--Secukupnya garam--1/2 sdt maizena,larutkan dg 100 ml air--', 'Siapkan bahan2--Goreng tahu smp matang..sementara itu kita rajang halus bumbu/diuleg jg boleh..--Siapkan minyak dwajan ±3 sdm,masukkan bumbu & petis,aduk rata. Biarkan smp harum. Lalu masukkan larutan maizena,aduk lg.. Icip smp dpt rasa yg pas.. Sajikan dgn tahu goreng... Sedapp--Drpd beli dluar,mending bkin sndiri yuk,rempong sdkit gpp demi kluarga trsayang..--', 'https://img-global.cpcdn.com/recipes/01da30aab09c8850/1360x964cq70/tahu-petis-musim-ujan-foto-resep-utama.webp\r'),
('43', 'Orek tempe manis pedas super simple', 'Orek tempe manis pedas super simple adalah salah satu masakan rumahan yang populer di Indonesia. Masakan ini terbuat dari tempe yang dipotong-potong kecil, kemudian dimasak dengan bumbu-bumbu sederhana seperti bawang merah, bawang putih, cabai, kecap manis, dan gula merah. ', 'Tempe (saya beli 3000 saja)--3 buah cabe gendot--3 buah cabe keriting--3 buah cabe rawit merah--2 siung bawang merah--1 siung bawang putih--Kecap--Saus tiram--Saus tomat--Kaldu bubuk--Garam--Gula--', 'Potong2 tempe sesuai selera lalu goreng sebentar.--Tumis duo bawang dan semua cabe (cabe bisa sesuai selera ya pedesnya suka segimana) sampai harum. Masukkan tempe, kecap, saus tiram, saus tomat, kaldu bubuk, gulgar, dan tambahkan air satu gelas belimbing. Aduk2 dan tutup wajan.--Saat air sudah menyusut dan kuah kecap mengental. Cek rasa. Klo sudah oke. Matikan api. Sajikan. (Klo aku suka airnya sedikit sekali 😋). Selamat mencoba !--', 'https://img-global.cpcdn.com/recipes/7dcc220d418b2cf0/1360x964cq70/orek-tempe-manis-pedas-super-simple-foto-resep-utama.webp\r'),
('44', 'Terik ayam tempe telor', 'Terik ayam tempe telor adalah salah satu masakan rumahan yang sederhana namun lezat. Masakan ini terbuat dari ayam, tempe, dan telur yang dimasak dengan kuah santan yang gurih dan kaya rempah. ', '4 sayap ayam--4 buah telor--1/2 papan tempe--Bumbu halus:--5 siung bawang merah--4 siung bawang putih--2 butir kemiri--1/2 sdm ketumbar--secukupnya Garam--Bumbu lain:--2 cm lengkuas--1 lembar daun salam--1 batang sereh--secukupnya Gula jawa--Bawang goreng--Minyak untuk menumis--1 bungkus santan kara--secukupnya Air--5 buah cabe rawit--', 'Cuci sayap ayam kemudian sisihkan. Rebus telur dan kupas. Sisihkan. Potong tempe sesuai selera. Sisihkan.--Panaskan minyak langsung di dalam panci. Tumis sereh, daun salam, dan lengkuas. Setelah beberapa saat masukkan bumbu halus. Tumis sampai berbau harum. Kemudian masukkan air dan gula jawa dan cabe rawit. Jika air sudah mendidih, masukkan sayap ayam dan telor. Masukkan tempe belakangan. Tunggu beberapa saat sampai ayam empuk (karena pakai sayap ayam, jadi tidak begitu lama). Jika ayam sudah empuk masukkan santan kara. Tunggu beberapa saat. Sesuaikan rasa. Matikan api, dan taburkan bawang goreng.--Terik siap dinikmati dengan nasi hangat dan kerupun 😁--', 'https://img-global.cpcdn.com/recipes/329d3523ee942c39/1360x964cq70/terik-ayam-tempe-telor-foto-resep-utama.webp\r'),
('45', 'Penyet Tempe Sambel Korek Kemangi', 'Penyet Tempe Sambel Korek Kemangi adalah salah satu hidangan khas Indonesia yang populer. Hidangan ini terdiri dari tempe yang digoreng dan dipenyet, kemudian disiram dengan sambal korek yang pedas dan harum. Kesegaran daun kemangi juga menambah cita rasa yang unik.', '2 buah tempe--1 genggam Daun kemangi--15 cabe rawit--2 siung bawang putih--Gula--Garam--', 'Iris tempe jd beberapa potong, bumbui dg bawang putih dan garam. Goreng sampai kering--Ulek cabe rawit dan 1 siung bawang putih ukuran besar tambah gula garam sesuai selera--Setelah halus tuang minyak goreng panas bekas goreng tempe td--Penyet tempe diatas sambel dan beri daun kemangi--Tempe penyet siap disantap 😋😋😋--', 'https://img-global.cpcdn.com/recipes/c3c11bf273933cbc/1360x964cq70/tempe-penyet-sambel-korek-kemangi-foto-resep-utama.webp\r');
INSERT INTO `Recipe` (`id`, `name`, `description`, `ingredients`, `step`, `urlimage`) VALUES
('46', 'Nugget tempe', 'Nugget tempe adalah makanan ringan yang terbuat dari tempe yang dihaluskan, dicampur dengan tepung, telur, dan bumbu-bumbu, kemudian dibentuk menjadi nugget dan digoreng. Nugget tempe memiliki rasa yang gurih dan renyah, serta kaya akan protein dan serat.', '1 papan tempe dihaluskan(saya kukus dlu)--1 buah wortel (parut kasar)--2 batang daun bawang (di iris kasar)--1 butir telur--3 butir bawang merah (di iris lalu di goreng)--3 butir bawang putih (di haluskan)--5 sdm tepung terigu--Secukupnya garam,lada & penyedap rasa--secukupnya Tepung panir--secukupnya Minyak goreng--', 'Campur tempe,wortel,daun bawang & bumbu yg sudah dihaluskan,beri garam,lada & penyedap rasa,tes rasa lalu masukkan telur--Bentuk adonan sesuai selera lalu gulingkan di tepung panir--Goreng hingga matang--Sajikan dengan saos sambal--', 'https://img-global.cpcdn.com/recipes/0409e384b1de6987/1360x964cq70/nugget-tempe-foto-resep-utama.webp\r'),
('47', 'Tempe tepung sajiku', 'Tempe tepung Sajiku adalah salah satu olahan tempe yang populer di Indonesia. Tempe dipotong-potong, kemudian dilapisi dengan tepung bumbu Sajiku yang sudah dicampur dengan air. Tempe goreng tepung Sajiku memiliki tekstur yang renyah di luar dan lembut di dalam. Rasanya pun gurih dan lezat.\n', '1 potong tempe 3000--1 bngkus sajiku tepung serbaguna--secukupnya Air--Minyak untuk manggoreng--', 'Potong tempe tipis2--Tuang tepung lalu beri air secukupnya--Panaskan minyak tunggu sampai panas--Masukan satu persatu--Tempe kedalam tepung sampai adonan habis--Angkat tiriskan dan sajikan dengan cabe rawit--', 'https://img-global.cpcdn.com/recipes/54389ab4e164aac2/1360x964cq70/tempe-tepung-sajiku-foto-resep-utama.webp\r'),
('48', 'Patty Tempe', 'Patty tempe adalah makanan perpaduan vegetarian yang terbuat dari tempe yang dihaluskan dan dicampur dengan bumbu-bumbu seperti bawang bombay, bawang putih, daun bawang, garam, dan merica. Patty tempe ini kemudian dibentuk bulat pipih dan digoreng hingga matang. ', '250 gram tempe, kukus, haluskan--150 gram daging sapi/ ayam (sy: 200 gr daging sapi)--5 sdm tepung panir (sy: tepung kobe putih)--2 butir telur--1 buah bawang bombay ukuran sedang, potong kotak kecil--4 siung bawang putih, memarkan lalu cincang--1/4 sdt merica bubuk--1/2 sdt garam--', 'Ini tepung kobe putih yg sy pakai.--Campur semua bahan dalam wadah.--Ulen hingga semua tercampur rata. Adonan menjadi padat. Tes rasa.--Bentuk bulat lalu pipihkan. Timbang per adonan bila perlu.--Siapkan teflon, beri 2 sdm minyak goreng, panaskan. Masukkan adonan. Masak hingga bagian bawah adonan kecoklatan, lalu balik, masak kembali hingga kecoklatan. Angkat, dinginkan, siap untuk isian burger. Atau mau dimakan gitu aja di cocol saus sambal jg enakkk.--Bila akan di simpan di freezer, sebaiknya panggang di teflon setengah matang, biarkan dingin, lalu masukkan dalam wadah tertutup atau plastik. (sengaja sy simpan 1 buah selama 2 minggu, setelah di goreng ttp oke rasanya).--Selamat Mencoba 😃--', 'https://img-global.cpcdn.com/recipes/ec20b57e12ef781f/1360x964cq70/patty-tempe-foto-resep-utama.webp\r'),
('49', 'Orek tempe basah bumbu ulek (recook)', 'Orek tempe basah bumbu ulek (recook) adalah masakan sederhana yang terbuat dari tempe goreng setengah matang yang dimasak dengan bumbu ulek yang terdiri dari bawang merah, bawang putih, cabai merah, kemiri, dan tomat. Masakan ini memiliki cita rasa gurih, manis, dan pedas yang menggugah selera. Orek tempe basah bumbu ulek cocok disajikan sebagai lauk pendamping nasi, lontong, atau ketupat.', '1 papan tempe, potong sesuai selera (sy 1/2 papan tempe+4 tahu)--3 cabe ijo, iris (sy lombok merah utuh)--Secukupnya kecap manis--Secukupnya gula, garam, penyedap (sy garam aja)--Secukupnya air--Bumbu halus:--5 butir bawang merah--2 siung bawang putih--1/2 buah tomat--3 cabe merah keriting/cabe rawit (sy skip)--2 butir kemiri--1/4 sdt ketumbar--', 'Goreng tempe setengah matang, angkat, tiriskan dan sisihkan.--Panaskan secukupnya minyak, tumis bumbu sampai layu dan harum. Tambahkan air, biarkan mendidih. Tambahkan kecap, lombok dan garam, aduk rata. Tambahkan tempe, aduk rata. Koreksi rasa. Angkat.--Siap disajikan.--', 'https://img-global.cpcdn.com/recipes/66e3da74d6cae09d/1360x964cq70/orek-tempe-basah-bumbu-ulek-recook-foto-resep-utama.webp\r'),
('5', 'Minyak Ayam', 'Minyak ayam dari ayam', '400 gr kulit ayam & lemaknya--8 siung bawang putih kating, cincang kasar--1 ruas jahe, geprek--350 ml minyak goreng--1 sdm ketumbar bubuk--', 'Cuci bersih kulit ayam. Sisihkan--Ambil 50 ml minyak goreng satu bahan yg sudah disiapkan tadi. Tumis jahe hingga harum.--Masukkan kulit ayam, ketumbar dan bawang. Biarkan hingga keluar minyak alaminya sambil diaduk-aduk.--Tambahkan sisa minyak goreng. Masak hingga kulit ayam mengering. Angkat dan saring.--Setelah cukup dingin minyak ayam tadi dapat disimpan dalam wadah kering seperti mason jar/botol. Kalo saya, saya masukkan juga sedikit bawang putih goreng.--Kulit ayam yg sudah digoreng kering tadi bisa dinikmati begitu saja sebagai camilan dengan ditaburi sejumput garam lalu aduk rata.--', 'https://img-global.cpcdn.com/recipes/c32bfa0b44270fa1/1360x964cq70/minyak-ayam-foto-resep-utama.webp\r'),
('50', 'Perkedel Tempe', 'Perkedel tempe adalah hidangan khas Indonesia yang terbuat dari tempe yang dihaluskan, dicampur dengan bumbu-bumbu, lalu digoreng. Perkedel tempe biasanya disajikan sebagai lauk pauk atau camilan. ', '1/2 potong papan tempe (haluskan dgn sedikit air)--bumbu halus: ulek kasar--6 siung bawang merah--2 siung bawang putih--2 cabai rawit--1 sdt ketumbar bubuk--secukupnya garam, ebi--1/2 bungkus tepung racik bakwan--', 'Campurkan adonan tempe basah dengan bumbu halus, aduk rata--Panaskan wajan dgn minyak, tuang adonan per 1 sendok makan sampai adonan habis--Goreng adonan sampai berwarna kekuningan--', 'https://img-global.cpcdn.com/recipes/53a861362a6e8d85/1360x964cq70/perkedel-tempe-foto-resep-utama.webp\r'),
('51', 'Nugget Tempe Simple', 'Nugget tempe adalah camilan atau lauk yang terbuat dari tempe yang dihaluskan, dicampur dengan tepung terigu, telur, dan bumbu-bumbu, kemudian dilumuri tepung panir dan digoreng. Nugget tempe merupakan salah satu hidangan olahan tempe yang populer di Indonesia. Hidangan ini memiliki rasa yang gurih dan renyah, serta memiliki kandungan protein yang tinggi.', '1 papan tempe--1 buah wortel--1 butir telur (kocok lepas)--5 siung bawang merah--2 siung bawang putih--2 batang daun bawang--1 sdt garam--Secukupnya: tepung terigu, merica, tepung roti & kaldu bubuk--', 'Haluskan bawang merah, bawang putih, merica, garam & kaldu bubuk. Tambahkan tempe, uleg sampai lembut--Potong2 daun bawang & parut wortel menggunakan parutan keju, siapkan baskom--Masukkan semua bahan dalam baskom kecuali telur & tepung roti. Tambahkan air & terigu, aduk rata. Masukkan dalam loyang & kukus selama 30 menit--Angkat, setelah dingin potong2 sesuai selera, celupkan dalam telur & gulingkan dalam tepung roti, simpan dalam freezer 30 menit. Lalu goreng. 🍱--', 'https://img-global.cpcdn.com/recipes/5698f35509f538be/1360x964cq70/nugget-tempe-simple-foto-resep-utama.webp\r'),
('6', 'Nasi Bakar Ayam', 'Nasi bakar dengan ayam yang sangat lezat', '1 piring nasi--¹/⁴ fillet ayam, potong kotak, cuci bersih--Daun pisang yang sudah dibersihkan--Lidi/tusuk gigi untuk mengapit daun--1 lbr daun salam--3 cm serai, memarkan--1 ikat daun kemangi, opsional--1 cabe merah besar, iris tipis--1 sdt kecap manis--Minyak untuk menumis--100 ml air--Bumbu Halus:--1 cabe merah besar--3 cabe kecil--2 siung bawang merah--1 siung bawang putih--1 kemiri--1 cm kunyit--¹/² ruas jahe--¹/⁴ tomat--1 sdt gula pasir--1 blok kaldu ayam (aku biasa pake maggy) pake royco, masako--Merica (dikira2 z takar nya, aku sdkit z sih)--', 'Tumis bumbu halus, masukkan daun salam, serai--Masukkan potongan ayam, kecap dan air, masak hingga air menyusut dan koreksi rasa--Masukkan irisan cabe merah dan daun kemangi, aduk sebentar dan matikan api--Tata daun pisang, tata nasi di atas daun, beri isian ayam atau bisa juga nasi di campur dan diaduk dulu dengan ayam baru di tata di daun Pisang, bunbu ayam akan lebih meresap k nasi--Setelah nasi di bungkus, barulah nasi di bakar, aku bakar pake teflon z br cepet 😀😀--Sajikan selagi hangat 👍👍endeusss--Note: Jangan membakar terlalu lama biar nasi ga kotor dari daun yg di bakar kering--', 'https://img-global.cpcdn.com/recipes/0d6cbfdef86dad7d/1360x964cq70/nasi-bakar-ayam-foto-resep-utama.webp\r'),
('7', 'Ayam Saus Hintalu Jaruk', 'yam saus hintalu jaruk adalah salah satu hidangan khas Sumatera Selatan yang sangat populer. Hidangan ini terbuat dari ayam yang digoreng terlebih dahulu, kemudian dimasak dengan saus telur asin yang gurih dan creamy. Ayam saus hintalu jaruk biasanya disajikan dengan nasi putih hangat dan taburan bawang goreng.', '1/2 Ekor ayam--2 Butir Hintalu Jaruk--1 Buah Cabe merah--1 Buah Cabe hijau--300 gr Tepung terigu--1 bks Merica bubuk--2 Siung Bawang putih--1 Buah jeruk nipis--secukupnya Minyak goreng untuk menumis dan menggoreng--secukupnya Gula, garam dan penyedap rasa--', 'Potong ayam menjadi kotak-kotak ukuran sedang cuci bersih kemudian lumuri perasan jeruk nipis, garam dan merica--Buat adonan tepung untuk melapisi ayam. Adonan A (Tepung terigu, garam, merica, penyedap dan air es) dan adonan B (Tepung terigu, garam, merica dan penyedap)--Masukan daging ayam kedalam adonan A kemudian lapisi dengan adonan B, setelah itu goreng daging kedalam minyak panas sampai berwarna kuning keemasan. Angkat tiriskan--Cincang bawang putih,iris seron cabe merah dan cabe hijau. Lumatkan kuning hintalu jaruk aka telur asin dengan air dingin sampai berbentuk pasta--Tumis bawang putih dan cabe sampai harum, kemudian tuangkan ayam dan pasta kuning telur.--Tambahkan gula, garam, penyedap dan merica secukupnya. Tes rasa dan masal hingga mengental--Angkat dan sajikan bersama nasi putih panas. Selamat mencoba--', 'https://img-global.cpcdn.com/recipes/e1a6c617116df583/1360x964cq70/ayam-saus-telur-asin-foto-resep-utama.webp\r'),
('8', 'Steak ayam', 'Steak ayam adalah hidangan daging ayam yang dimasak dengan cara dibakar atau dipanggang. Daging ayam yang digunakan biasanya adalah dada ayam fillet atau paha ayam fillet. Steak ayam dapat disajikan dengan berbagai macam saus, seperti saus barbekyu, saus tiram, atau saus asam manis.', '300 gr dada ayam fillet--1 sdm air jeruk nipis--secukupnya garam--adonan basah--50 gr terigu--10 gr maizena--1/4 sdt merica--garam--secukupnya air--adonan kering--150 gr terigu--30 gr maizena--1/2 sdt merica bubuk--1/4 sdt kaldu jamur--secukupnya garam--secukupnya minyak goreng--bahan saus jamur--50 gr jamur tiram blender--3 bawang putih cincang halus--20 gr keju parut--1 sdm maizena cairkan dgn air--2 sdm saus tiram--1 sdm kecap manis--1/2 sdt merica halus--secukupnya garam & kaldu jamur--air--bahan pelengkap--buncis dan wortel di kukus--', 'Cuci bersih ayam, iris tipis melebar, rendam dgn garam dan air jeruk nipis 10 menit, cuci--Campur adonan kering, sisihkan--Campur adonan basah, sisihkan--Panaskan minyak goreng dgn api sedang, gulingkan ayam pada adonan kering, lalu celup ke adonan basah, gulingkan lg pada adonan kering, jgn di remas2, kibas2 daging ayam pada adonan kering, lalu goreng di minyak yg banyak dan panas, biarkan krispinya terbentuk dl, jgn di balik2 dl, setelah cukup kering br di balik, goreng smpe matang, tiriskan--Blender jamur tiram kasih air sedikit. tumis bawang putih yg di cincang halus, masukkan jamur yg di blender, masukkan bumbu2 yg lain sampai meresap, lalu tuang maizena yg sdh di cairkan dgn setengah gelas air, aduk2, masukkan keju parut, aduk sampai meletup2, tes rasa, klo sdh sesuai, angkat--Tata dlm piring, ayam goreng tepung dan sayur kukus, siram dgn saus jamur, taburi daun bawang atau parsley jk ada.--', 'https://img-global.cpcdn.com/recipes/92e89c34bdee7bbb/1360x964cq70/steak-ayam-foto-resep-utama.webp\r'),
('9', 'Gurame Saus Padang', 'Gurame saus Padang adalah salah satu hidangan khas Indonesia yang sangat populer. Hidangan ini terbuat dari ikan gurame yang digoreng garing dan disajikan dengan saus Padang yang pedas dan gurih. Saus Padang terbuat dari cabai merah, bawang merah, bawang putih, tomat, dan rempah-rempah lainnya. ', 'Bahan utama:--1 ekor gurame--Bumbu untuk saus:--4 siung bawang putih (cincang halus)--3 siung bawang merah (cincang halus)--15 bh cabai merah (giling) banyaknya cabai sesuai selera ya😊--7 buah cabai rawit iris tipis (sesuai selera)--1/2 bawang bombang iris--Saus tiram--Saus tomat--Garam--Gula--Lada--1 bh wortel iris tipis memanjang (opsional)--1 buah tomat potong dadu (opsional)--1 batang irisan daun bawang--1 ruas jahe ukuran kecil iris tipis--Tepung maizena--250 ml air--Bumbu untuk menggoreng ikan :--Tepung beras--Tepung terigu--Garam--Jeruk nipis/ lemon--Minyak sayur--', 'Cuci bersih ikan gurame yang akan dimasak. Setelah itu lumuri ikan dengan air perasan jeruk nipis/lemon diamkan beberapa menit untuk menghilangkan bau amisnya--Campur tepung terigu,tepung beras dan garam menjadi satu,kemudian lumuri ikan dengan tepung tersebut lalu goreng hingga matang lalu tiriskan. Pastikan minyak yang digunakan sudah panas ya biar ikannya tidak lengket😊.--Tumis bawang merah bawang putih hingga harum,kemudian masukan cabai yang sudah giling, aduk rata--Tambahkan bawang bombay,saus tiram saus tomat dan jahe, aduk sebentar lalu tambahkan 250ml air--Kemudian tambahkan garam dan gula sesuai selera.--Masukkan irisan cabai rawit dan daun bawang dan tomat. Aduk rata. Kemudian tambahkan larutan maizena agar saus mengental--Jika tidak ada tepung maizena. Diamkan beberapa menit hingga kandungan air menyusut dan saus terlihat mengental--Tes rasa. Jika sudah pas. Sajikan dan gurame saus padang siap disantap!😊--', 'https://img-global.cpcdn.com/recipes/18208822229e63b5/1360x964cq70/gurame-saus-padang-foto-resep-utama.webp\r');

-- --------------------------------------------------------

--
-- Struktur dari tabel `User`
--

CREATE TABLE `User` (
  `id` varchar(191) NOT NULL,
  `name` varchar(191) NOT NULL,
  `username` varchar(191) NOT NULL,
  `email` varchar(191) NOT NULL,
  `password` varchar(191) NOT NULL,
  `timestamp` datetime(3) NOT NULL DEFAULT current_timestamp(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data untuk tabel `User`
--

INSERT INTO `User` (`id`, `name`, `username`, `email`, `password`, `timestamp`) VALUES
('0d1b70a8-ea3e-490f-ba10-7e2935cbbf92', 'Endang Kusnaedi', 'endangkus', 'endangkus@gmail.com', '$2b$10$Oi6El5DDVb1GB4OIA8WB8OZo6iulTFH/6K9QC3kWkMLngxB0OAjKe', '2023-12-10 12:10:04.753'),
('112ba2ad-3066-4b6e-b2c2-fa9bab8bb720', 'EDI JUNED', 'edijuned', 'edijuned@gmail.com', '$2b$10$SLfaSkBDd9wpEb.h0/3R7eUdQ9tZM7CZk1jK0eM0OjszXUrQGgIPS', '2023-12-06 14:48:47.550'),
('fd3d56a0-3bea-40ff-9ce9-780046291d31', 'Fadli Izurohman', 'fadlii', 'fadliizurohman@gmail.com', '$2b$10$O4u4TBSDWqRJQVX/FCNXwOviRlNtb/mlRs6erasIqrK9xpJIZpG1.', '2023-12-07 08:44:23.710');

-- --------------------------------------------------------

--
-- Struktur dari tabel `_prisma_migrations`
--

CREATE TABLE `_prisma_migrations` (
  `id` varchar(36) NOT NULL,
  `checksum` varchar(64) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `migration_name` varchar(255) NOT NULL,
  `logs` text DEFAULT NULL,
  `rolled_back_at` datetime(3) DEFAULT NULL,
  `started_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `applied_steps_count` int(10) UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data untuk tabel `_prisma_migrations`
--

INSERT INTO `_prisma_migrations` (`id`, `checksum`, `finished_at`, `migration_name`, `logs`, `rolled_back_at`, `started_at`, `applied_steps_count`) VALUES
('0335d44c-dae2-42da-a97c-35159cdb3d54', 'd3e0243001ed53e50c73801bae13a35dae40258076fe277e355568aabc57a248', '2023-12-20 06:04:53.678', '20231220060453_add_image', NULL, NULL, '2023-12-20 06:04:53.667', 1),
('415cfbe3-1698-451f-abe1-5131bf547d2c', '982db754e46477e733378452341b04219b512121e4bc7a6dcb94ceb1027c44f6', '2023-12-20 09:23:11.333', '20231220092311_add_user', NULL, NULL, '2023-12-20 09:23:11.320', 1),
('8c313d9f-7ef3-4637-8009-6e5e8003aff8', 'f3d6312f91e0c4a587f71642057621acdd774c743e6ec2e6c06a62a594cb42f1', '2023-12-06 14:39:18.318', '20231206143918_init', NULL, NULL, '2023-12-06 14:39:18.261', 1),
('9eead6f4-3127-4d00-9ae2-789d5f425d72', '34d42575cee3dbee0c2b9fa49472988e80d54137d03c7ab6879623c71e814b8f', '2023-12-20 09:22:21.398', '20231220092221_add_bahan', NULL, NULL, '2023-12-20 09:22:21.376', 1),
('f93a18ab-23b9-4db9-be6c-3ffde89e9d52', '007409d3ff2fa81aadbc4c9e732ba5450df83c0355da1e38a166c643e0660455', '2023-12-20 05:45:42.370', '20231220054435_migration_bahan', NULL, NULL, '2023-12-20 05:45:42.361', 1);

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `Bahan`
--
ALTER TABLE `Bahan`
  ADD PRIMARY KEY (`id`);

--
-- Indeks untuk tabel `Favourite`
--
ALTER TABLE `Favourite`
  ADD PRIMARY KEY (`id`),
  ADD KEY `Favourite_user_id_fkey` (`user_id`),
  ADD KEY `Favourite_recipe_id_fkey` (`recipe_id`);

--
-- Indeks untuk tabel `History`
--
ALTER TABLE `History`
  ADD PRIMARY KEY (`id`),
  ADD KEY `History_user_id_fkey` (`user_id`),
  ADD KEY `History_recipe_id_fkey` (`recipe_id`);

--
-- Indeks untuk tabel `Pantry`
--
ALTER TABLE `Pantry`
  ADD PRIMARY KEY (`id`),
  ADD KEY `Pantry_bahan_id_fkey` (`bahan_id`),
  ADD KEY `Pantry_user_id_fkey` (`user_id`);

--
-- Indeks untuk tabel `Recipe`
--
ALTER TABLE `Recipe`
  ADD PRIMARY KEY (`id`);

--
-- Indeks untuk tabel `User`
--
ALTER TABLE `User`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `User_name_key` (`name`),
  ADD UNIQUE KEY `User_username_key` (`username`),
  ADD UNIQUE KEY `User_email_key` (`email`);

--
-- Indeks untuk tabel `_prisma_migrations`
--
ALTER TABLE `_prisma_migrations`
  ADD PRIMARY KEY (`id`);

--
-- Ketidakleluasaan untuk tabel pelimpahan (Dumped Tables)
--

--
-- Ketidakleluasaan untuk tabel `Favourite`
--
ALTER TABLE `Favourite`
  ADD CONSTRAINT `Favourite_recipe_id_fkey` FOREIGN KEY (`recipe_id`) REFERENCES `Recipe` (`id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `Favourite_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`) ON UPDATE CASCADE;

--
-- Ketidakleluasaan untuk tabel `History`
--
ALTER TABLE `History`
  ADD CONSTRAINT `History_recipe_id_fkey` FOREIGN KEY (`recipe_id`) REFERENCES `Recipe` (`id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `History_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`) ON UPDATE CASCADE;

--
-- Ketidakleluasaan untuk tabel `Pantry`
--
ALTER TABLE `Pantry`
  ADD CONSTRAINT `Pantry_bahan_id_fkey` FOREIGN KEY (`bahan_id`) REFERENCES `Bahan` (`id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `Pantry_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`) ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
